baseURL = 'https://www.mattpeake.com/'
languageCode = 'en-us'
title = 'mattpeake'

disableKinds = ["taxonomy"]
ignoreErrors = ["error-disable-taxonomy"] # you will get a console error message without this

[menu]
[[menu.main]]
  name = 'gallery'
  url = '/gallery'
  weight = 10
[[menu.main]]
  name = 'projects'
  url = '/projects'
  weight = 20